// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xCourse.Entities;

namespace xCourse.Migrations
{
    [DbContext(typeof(FlowchartContext))]
    [Migration("20201122163015_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("xCourse.Entities.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseCodeAbbriviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SemesterID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("xCourse.Entities.Degree", b =>
                {
                    b.Property<string>("DegreeAbbriviation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DegreeAbbriviation");

                    b.ToTable("Degree");
                });

            modelBuilder.Entity("xCourse.Entities.Semester", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DegreeAbbriviation")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("DegreeAbbriviation");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("xCourse.Entities.Course", b =>
                {
                    b.HasOne("xCourse.Entities.Course", null)
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseID");

                    b.HasOne("xCourse.Entities.Semester", null)
                        .WithMany("Courses")
                        .HasForeignKey("SemesterID");
                });

            modelBuilder.Entity("xCourse.Entities.Semester", b =>
                {
                    b.HasOne("xCourse.Entities.Degree", null)
                        .WithMany("Semesters")
                        .HasForeignKey("DegreeAbbriviation");
                });
#pragma warning restore 612, 618
        }
    }
}
